export const FETCH_ITEM_REQUEST = 'app/HOME_PAGE/FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'app/HOME_PAGE/FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'app/HOME_PAGE/FETCH_ITEM_FAILURE';

export const FETCH_ITEM_LIST_REQUEST = 'app/HOME_PAGE/FETCH_ITEM_LIST_REQUEST';
export const FETCH_ITEM_LIST_SUCCESS = 'app/HOME_PAGE/FETCH_ITEM_LIST_SUCCESS';
export const FETCH_ITEM_LIST_FAILURE = 'app/HOME_PAGE/FETCH_ITEM_LIST_FAILURE';

export const CREATE_ITEM_REQUEST = 'app/HOME_PAGE/CREATE_ITEM_REQUEST';
export const CREATE_ITEM_SUCCESS = 'app/HOME_PAGE/CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAILURE = 'app/HOME_PAGE/CREATE_ITEM_FAILURE';

export const UPDATE_ITEM_REQUEST = 'app/HOME_PAGE/UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'app/HOME_PAGE/UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'app/HOME_PAGE/UPDATE_ITEM_FAILURE';

export const DELETE_ITEM_REQUEST = 'app/HOME_PAGE/DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'app/HOME_PAGE/DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'app/HOME_PAGE/DELETE_ITEM_FAILURE';


export const FETCH_CATEGORY_REQUEST = 'app/HOME_PAGE/FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'app/HOME_PAGE/FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILURE = 'app/HOME_PAGE/FETCH_CATEGORY_FAILURE';

export const FETCH_CATEGORY_LIST_REQUEST = 'app/HOME_PAGE/FETCH_CATEGORY_LIST_REQUEST';
export const FETCH_CATEGORY_LIST_SUCCESS = 'app/HOME_PAGE/FETCH_CATEGORY_LIST_SUCCESS';
export const FETCH_CATEGORY_LIST_FAILURE = 'app/HOME_PAGE/FETCH_CATEGORY_LIST_FAILURE';

export const CREATE_CATEGORY_REQUEST = 'app/HOME_PAGE/CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'app/HOME_PAGE/CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'app/HOME_PAGE/CREATE_CATEGORY_FAILURE';

export const UPDATE_CATEGORY_REQUEST = 'app/HOME_PAGE/UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'app/HOME_PAGE/UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE = 'app/HOME_PAGE/UPDATE_CATEGORY_FAILURE';

export const DELETE_CATEGORY_REQUEST = 'app/HOME_PAGE/DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'app/HOME_PAGE/DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'app/HOME_PAGE/DELETE_CATEGORY_FAILURE';


export const OPEN_NEW_ITEM_MODAL = 'app/HOME_PAGE/OPEN_NEW_ITEM_MODAL';
export const OPEN_NEW_CATEGORY_MODAL = 'app/HOME_PAGE/OPEN_NEW_CATEGORY_MODAL';
export const OPEN_ITEM_MODAL = 'app/HOME_PAGE/OPEN_ITEM_MODAL';
export const CLOSE_MODAL = 'app/HOME_PAGE/CLOSE_MODAL';
